class AddTotalsToDays < ActiveRecord::Migration[6.1]
  def change
    add_column :days, :energykj, :integer, default: 0
    add_column :days, :energykcal, :integer, default: 0
    add_column :days, :energyfibrekj, :integer, default: 0
    add_column :days, :energyfibrekcal, :integer, default: 0
    add_column :days, :eau, :integer, default: 0
    add_column :days, :proteinesjones, :integer, default: 0
    add_column :days, :proteines, :integer, default: 0
    add_column :days, :glucides, :integer, default: 0
    add_column :days, :lipides, :integer, default: 0
    add_column :days, :sucres, :integer, default: 0
    add_column :days, :fructose, :integer, default: 0
    add_column :days, :galactos, :integer, default: 0
    add_column :days, :glucose, :integer, default: 0
    add_column :days, :lactose, :integer, default: 0
    add_column :days, :maltose, :integer, default: 0
    add_column :days, :saccharose, :integer, default: 0
    add_column :days, :amidon, :integer, default: 0
    add_column :days, :fibres, :integer, default: 0
    add_column :days, :polyols, :integer, default: 0
    add_column :days, :cendres, :integer, default: 0
    add_column :days, :alcool, :integer, default: 0
    add_column :days, :acideorganiques, :integer, default: 0
    add_column :days, :agsatures, :integer, default: 0
    add_column :days, :agmonoinsature, :integer, default: 0
    add_column :days, :agpolyinsature, :integer, default: 0
    add_column :days, :agbutyrique, :integer, default: 0
    add_column :days, :agcaproique, :integer, default: 0
    add_column :days, :agcaprylique, :integer, default: 0
    add_column :days, :agcaprique, :integer, default: 0
    add_column :days, :aglaurique, :integer, default: 0
    add_column :days, :agmyristique, :integer, default: 0
    add_column :days, :agpalmitique, :integer, default: 0
    add_column :days, :agstearique, :integer, default: 0
    add_column :days, :agoleique, :integer, default: 0
    add_column :days, :aglinoeique, :integer, default: 0
    add_column :days, :agalphalinolenique, :integer, default: 0
    add_column :days, :agarachidoneique, :integer, default: 0
    add_column :days, :ageap, :integer, default: 0
    add_column :days, :agdha, :integer, default: 0
    add_column :days, :cholesterole, :integer, default: 0
    add_column :days, :sel, :integer, default: 0
    add_column :days, :calcium, :integer, default: 0
    add_column :days, :chlorure, :integer, default: 0
    add_column :days, :cuivre, :integer, default: 0
    add_column :days, :fer, :integer, default: 0
    add_column :days, :iode, :integer, default: 0
    add_column :days, :magnesium, :integer, default: 0
    add_column :days, :manganese, :integer, default: 0
    add_column :days, :phosphore, :integer, default: 0
    add_column :days, :potassium, :integer, default: 0
    add_column :days, :selenium, :integer, default: 0
    add_column :days, :sodium, :integer, default: 0
    add_column :days, :zinc, :integer, default: 0
    add_column :days, :retinol, :integer, default: 0
    add_column :days, :betacarotene, :integer, default: 0
    add_column :days, :vitamineD, :integer, default: 0
    add_column :days, :vitamineE, :integer, default: 0
    add_column :days, :vitamineK1, :integer, default: 0
    add_column :days, :vitamineK2, :integer, default: 0
    add_column :days, :vitamineC, :integer, default: 0
    add_column :days, :vitamineB1, :integer, default: 0
    add_column :days, :vitamineB2, :integer, default: 0
    add_column :days, :vitamineB3, :integer, default: 0
    add_column :days, :vitamineB5, :integer, default: 0
    add_column :days, :vitamineB6, :integer, default: 0
    add_column :days, :vitamineB9, :integer, default: 0
    add_column :days, :vitamineB12, :integer, default: 0
  end
end
