class AddTotalsToDays < ActiveRecord::Migration[6.1]
  def change
    add_column :days, :energykj, :integer
    add_column :days, :energykcal, :integer
    add_column :days, :energyfibrekj, :integer
    add_column :days, :energyfibrekcal, :integer
    add_column :days, :eau, :integer
    add_column :days, :proteinesjones, :integer
    add_column :days, :proteines, :integer
    add_column :days, :glucides, :integer
    add_column :days, :lipides, :integer
    add_column :days, :sucres, :integer
    add_column :days, :fructose, :integer
    add_column :days, :galactos, :integer
    add_column :days, :glucose, :integer
    add_column :days, :lactose, :integer
    add_column :days, :maltose, :integer
    add_column :days, :saccharose, :integer
    add_column :days, :amidon, :integer
    add_column :days, :fibres, :integer
    add_column :days, :polyols, :integer
    add_column :days, :cendres, :integer
    add_column :days, :alcool, :integer
    add_column :days, :acideorganiques, :integer
    add_column :days, :agsatures, :integer
    add_column :days, :agmonoinsature, :integer
    add_column :days, :agpolyinsature, :integer
    add_column :days, :agbutyrique, :integer
    add_column :days, :agcaproique, :integer
    add_column :days, :agcaprylique, :integer
    add_column :days, :agcaprique, :integer
    add_column :days, :aglaurique, :integer
    add_column :days, :agmyristique, :integer
    add_column :days, :agpalmitique, :integer
    add_column :days, :agstearique, :integer
    add_column :days, :agoleique, :integer
    add_column :days, :aglinoeique, :integer
    add_column :days, :agalphalinolenique, :integer
    add_column :days, :agarachidoneique, :integer
    add_column :days, :ageap, :integer
    add_column :days, :agdha, :integer
    add_column :days, :cholesterole, :integer
    add_column :days, :sel, :integer
    add_column :days, :calcium, :integer
    add_column :days, :chlorure, :integer
    add_column :days, :cuivre, :integer
    add_column :days, :fer, :integer
    add_column :days, :iode, :integer
    add_column :days, :magnesium, :integer
    add_column :days, :manganese, :integer
    add_column :days, :phosphore, :integer
    add_column :days, :potassium, :integer
    add_column :days, :selenium, :integer
    add_column :days, :sodium, :integer
    add_column :days, :zinc, :integer
    add_column :days, :retinol, :integer
    add_column :days, :betacarotene, :integer
    add_column :days, :vitamineD, :integer
    add_column :days, :vitamineE, :integer
    add_column :days, :vitamineK1, :integer
    add_column :days, :vitamineK2, :integer
    add_column :days, :vitamineC, :integer
    add_column :days, :vitamineB1, :integer
    add_column :days, :vitamineB2, :integer
    add_column :days, :vitamineB3, :integer
    add_column :days, :vitamineB5, :integer
    add_column :days, :vitamineB6, :integer
    add_column :days, :vitamineB9, :integer
    add_column :days, :vitamineB12, :integer
  end
end
