class Day < ApplicationRecord
  validates :date, presence: true, uniqueness: true
  validates :comment, length: {maximum: 120}, allow_blank: true
  has_many :pooh, dependent: :destroy
  belongs_to :user
  has_many :meals, dependent: :destroy

  CATEGORIES = [
    'energykj',
    'energykcal',
    'energyfibrekj',
    'energyfibrekcal',
    'eau',
    'proteinesjones',
    'proteines',
    'glucides',
    'lipides',
    'sucres',
    'fructose',
    'galactos',
    'glucose',
    'lactose',
    'maltose',
    'saccharose',
    'amidon',
    'fibres',
    'polyols',
    'cendres',
    'alcool',
    'acideorganiques',
    'agsatures',
    'agmonoinsature',
    'agpolyinsature',
    'agbutyrique',
    'agcaproique',
    'agcaprylique',
    'agcaprique',
    'aglaurique',
    'agmyristique',
    'agpalmitique',
    'agstearique',
    'agoleique',
    'aglinoeique',
    'agalphalinolenique',
    'agarachidoneique',
    'ageap',
    'agdha',
    'cholesterole',
    'sel',
    'calcium',
    'chlorure',
    'cuivre',
    'fer',
    'iode',
    'magnesium',
    'manganese',
    'phosphore',
    'potassium',
    'selenium',
    'sodium',
    'zinc',
    'retinol',
    'betacarotene',
    'vitamineD',
    'vitamineE',
    'vitamineK1',
    'vitamineK2',
    'vitamineC',
    'vitamineB1',
    'vitamineB5',
    'vitamineB6',
    'vitamineB12'
  ]
end
